spring:
  application:
    name: GBGS-Discovery-service
  boot:
    admin:
      context-path: /admin

server:
  port: 8762
  tomcat:
    uri-encoding: utf-8
eureka:
  client:
    service-url:
      defaultZone : http://${security.user.name}:${security.user.password}@peer1:8761/eureka/
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    hostname: peer2

security:
  basic:
    enabled: true
  user:
    name: root
    password: admin